# Generated by Django 4.2.3 on 2023-09-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfooditem',
            name='food_price',
        ),
    ]
